In [2]:
from scipy.stats import chi2_contingency
import pandas as pd
import numpy as np

In [4]:
observedBelts = pd.DataFrame([
    [175,20,42,6],
    [149,17,41,9]
    ],
    index=['seatbelt', 'no-belt'],
    columns=['0 cigs', '1-14', '15-34', '>35'])

In [5]:
chi2_contingency(observedBelts)

(1.358175464062902,
 0.7153672395500257,
 3,
 array([[171.52941176,  19.58823529,  43.94117647,   7.94117647],
        [152.47058824,  17.41176471,  39.05882353,   7.05882353]]))

In [6]:
show = pd.DataFrame([
    [45,78,36],
    [127,153,54],
    [65,23,148]
    ],
    index=['-21', '21-50', '50+'],
    columns=['survivor', 'Big Bro', 'Amaze race'])


In [7]:
chi2_contingency(show)

(167.18889381024792,
 4.195027833023578e-35,
 4,
 array([[ 51.69135802,  55.39917695,  51.90946502],
        [108.58436214, 116.37311385, 109.04252401],
        [ 76.72427984,  82.22770919,  77.04801097]]))

In [10]:
sports = pd.DataFrame([
    [127,53,50,57],
    [71,47,43,42]
    ],
    index=['home wins', 'visitor wins'],
    columns=['NBA', 'MLB', 'NHL', 'NFL'])

In [11]:
chi2_contingency(sports)

(4.737208762521437,
 0.19208284575582948,
 3,
 array([[115.97142857,  58.57142857,  54.47142857,  57.98571429],
        [ 82.02857143,  41.42857143,  38.52857143,  41.01428571]]))

In [ ]:
from